include:
  #- board: corneish_zen_v2_left
    # snippet: zmk-usb-logging  # uncomment to enable logging
 # - board: corneish_zen_v2_right
 # - board: corneish_zen_v2_left
---
include:
  - board: nice_nano_v2
    shield: corne_ish_zen_left
  - board: nice_nano_v2
    shield: corne_ish_zen_right
